import type { Metadata } from "next";
import "./globals.css";
import { Web3Provider } from "./providers/web3Init";
import { LangChainProvider } from "./providers/langchain";
import { WrappedEtherProvider } from "./providers/WrappedEther";
import { CowSwapProvider } from "./providers/CowSwap";
import { OneinchProvider } from "./providers/Oneinch";
import Poppins from "./fonts/poppins";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Poppins.className} antialiased bg-white text-black text-center`}
      >
        <Web3Provider>
          <WrappedEtherProvider>
            <CowSwapProvider>
              <OneinchProvider>
                <LangChainProvider>{children}</LangChainProvider>
              </OneinchProvider>
            </CowSwapProvider>
          </WrappedEtherProvider>
        </Web3Provider>
      </body>
    </html>
  );
}
